{ config, lib, pkgs, ...  }: {
  imports = [
    # auto-generated by nixos
    ./hardware-configuration.nix

    ../common-desktop
    ./boot.nix
    ./filesystems.nix
    ./hardware.nix
    ./programs.nix
  ];

  # use fcitx5 for ime
  i18n.inputMethod = {
    enabled = "fcitx5";
    fcitx5.waylandFrontend = true;
  };

  networking.hostName = "oyasumi";

  # set the time zone
  time.timeZone = "Asia/Ho_Chi_Minh";
}
